heroes = [
  {
    game_id: 1,
    name: "D.Va",
    role_id: 1,
    can_heal_self: false,
    heal_self_strength: nil,
    has_cc: true,
    # cc_strength: ,
    hp: 600,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    cc_range: 0,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: true,
    provides_shield: true,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: true
  },
  {
    game_id: 1,
    name: "Orisa",
    role_id: 1,
    can_heal_self: false,
    heal_self_strength: nil,
    has_cc: false,
    # cc_strength: ,
    # cc_range: 0,
    hp: 200,
    shield: 0,
    armor: 250,
    has_shield: true,
    shield_hp: 600,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: false,
    # movement_speed: 
    can_fly: false,
    provides_shield: true,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false
  },
  {
    game_id: 1,
    name: "Reinhardt",
    role_id: 1,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: ,
    # cc_range: 0,
    hp: 500,
    shield: 0,
    armor: 0,
    has_shield: true,
    shield_hp: 1500,
    melee_primary_fire: true,
    aoe_heal: false,
    aoe_primary: true,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: false,
    provides_shield: true,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false
  },
  {
    game_id: 1,
    name: "Sigma",
    role_id: 1,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: true,
    cc_strength: 800, # milliseconds duration
    cc_range: 25, # meters
    hp: 300,
    shield: 100,
    armor: 0,
    has_shield: true,
    shield_hp: 700,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: false,
    # movement_speed: 
    can_fly: false,
    provides_shield: true,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false
  },
  {
    game_id: 1,
    name: "Winston",
    role_id: 1,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 350,
    shield: 0,
    armor: 150,
    has_shield: true,
    shield_hp: 700,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: true,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: false,
    provides_shield: true,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false
  },
  {
    game_id: 1,
    name: "Wrecking Ball",
    role_id: 1,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: true,
    cc_strength: 500, # milliseconds duration
    cc_range: 2, # meters
    hp: 500,
    shield: 0,
    armor: 100,
    has_shield: true,
    shield_hp: 100,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: true,
    movement_speed: 10,
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: true
  },
  {
    game_id: 1,
    name: "Zarya",
    role_id: 1,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 200,
    shield: 200,
    armor: 0,
    has_shield: true,
    shield_hp: 200,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: false,
    # movement_speed: 
    can_fly: false,
    provides_shield: true,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: true
  },
  {
    game_id: 1,
    name: "Ashe",
    role_id: 2,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 200,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: false,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: true
  },
  {
    game_id: 1,
    name: "Cassidy",
    role_id: 2,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: true,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 225,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: false,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: true
  },
  {
    game_id: 1,
    name: "Doomfist",
    role_id: 2,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: true,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 250,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false
  },
  {
    game_id: 1,
    name: "Echo",
    role_id: 2,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 200,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: true,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false
  },
  {
    game_id: 1,
    name: "Genji",
    role_id: 2,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 200,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false
  },
  {
    game_id: 1,
    name: "Hanzo",
    role_id: 2,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 200,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: false,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false
  },
  {
    game_id: 1,
    name: "Junkrat",
    role_id: 2,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: true,
    cc_strength: 3000, # milliseconds duration
    cc_range: 0, # meters
    hp: 200,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false
  },
  {
    game_id: 1,
    name: "Pharah",
    role_id: 2,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 200,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: true,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: true,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false
  },
  {
    game_id: 1,
    name: "Sombra",
    role_id: 2,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 200,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: true
  },
  {
    game_id: 1,
    name: "Symmetra",
    role_id: 2,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: true,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 100,
    shield: 125,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: false,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: true,
    has_secondary_fire: true
  },
  {
    game_id: 1,
    name: "Torbjörn",
    role_id: 2,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 200,
    shield: 0,
    armor: 50,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: false,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false
  },
  {
    game_id: 1,
    name: "Tracer",
    role_id: 2,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 150,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: true
  },
  {
    game_id: 1,
    name: "Widowmaker",
    role_id: 2,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 175,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: true
  },
  {
    game_id: 1,
    name: "Zenyatta",
    role_id: 3,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 50,
    shield: 150,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: false,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: true,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false
  },
  {
    game_id: 1,
    name: "Moira",
    role_id: 3,
    can_heal_self: true,
    # heal_self_strength: ,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 200,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: true,
    aoe_primary: false,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: true,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: true
  },
  {
    game_id: 1,
    name: "Mercy",
    role_id: 3,
    can_heal_self: true,
    heal_self_strength: 20, # hp/sec
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 200,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: true,
    provides_shield: false,
    provides_damage_boost: true,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false
  },
  {
    game_id: 1,
    name: "Lúcio",
    role_id: 3,
    can_heal_self: true,
    # heal_self_strength: nil,
    has_cc: true,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 200,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: true,
    aoe_primary: false,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false,
    has_secondary_fire: true
  },
  {
    game_id: 1,
    name: "Brigitte",
    role_id: 3,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: true,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 150,
    shield: 0,
    armor: 50,
    has_shield: true,
    shield_hp: 250,
    melee_primary_fire: true,
    aoe_heal: true,
    aoe_primary: true,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false
  },
  {
    game_id: 1,
    name: "Baptiste",
    role_id: 3,
    can_heal_self: true,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 200,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: true,
    aoe_primary: false,
    has_escape_ability: false,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: true
  },
  {
    game_id: 1,
    name: "Zenyatta",
    role_id: 3,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 50,
    shield: 150,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: false,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: true,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false
  },
  {
    game_id: 1,
    name: "Ana",
    role_id: 3,
    can_heal_self: true,
    # heal_self_strength: nil,
    has_cc: true,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 200,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: false,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: true
  },
  {
    game_id: 1,
    name: "Roadhog",
    role_id: 1,
    can_heal_self: true,
    heal_self_strength: 37.5, # amount of healing per second (rename?)
    has_cc: true,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 600,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: false,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false,
    has_secondary_fire: true
  },
  {
    game_id: 1,
    name: "Bastion",
    role_id: 2,
    can_heal_self: true,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 200,
    shield: 0,
    armor: 100,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: false,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: true
  },
  {
    game_id: 1,
    name: "Mei",
    role_id: 2,
    can_heal_self: true,
    # heal_self_strength: nil,
    has_cc: true,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 250,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false,
    has_secondary_fire: true
  },
  {
    game_id: 1,
    name: "Reaper",
    role_id: 2,
    can_heal_self: true,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 250,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: true,
  },
  {
    game_id: 1,
    name: "Soldier: 76",
    role_id: 2,
    can_heal_self: true,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 200,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: true,
    aoe_primary: false,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: true
  },
]

heroes.each do |hero|
  existing_hero = Hero.find_or_create_by(hero)
end
