heroes = [
  {
    game_id: 1,
    name: "D.Va",
    role_id: 1,
    can_heal_self: false,
    heal_self_strength: nil,
    has_cc: true,
    # cc_strength: ,
    hp: 600,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    cc_range: 0,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: true,
    provides_shield: true,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false,
    abilities_attributes: [
      {
        keybinding: 'Left Click',
        cooldown: nil,
        duration: nil,
        has_aoe_effect: false,
        aoe_effect_radius: nil,
        base_beam_damage: nil,
        applies_burn: false,
        applies_speed_boost: false,
        applies_stun: false,
        applies_shield: false,
        cast_time: nil,
        applies_headshot_damage: true,
        burn_damage_per_second: nil,
        is_projectile: true,
        projectile_speed: -1,
        min_damage_per_projectile: 0.6,
        max_damage_per_projectile: 2,
        projectiles_fired_per_second: 73.37,
        max_range: nil,
        hp: nil,
        is_ultimate: false,
        ultimate_cost: nil,
        name: 'Fusion Cannons',
        is_passive: false,
        is_primary_fire: true,
        initial_falloff_distance: 10,
        final_falloff_disance: 20,
        spread_angle: 4.15,
        is_secondary_fire: false,
        is_beam: false,
        max_beam_damage: nil,
        reload_time: nil,
        fire_rate: 6.67,
        beam_width: nil
      },
      {
        keybinding: 'MOUSE1',
        cooldown: 1000,
        duration: 2000,
        has_aoe_effect: false,
        aoe_effect_radius: nil,
        base_beam_damage: nil,
        applies_burn: false,
        applies_speed_boost: false,
        applies_stun: false,
        applies_shield: false,
        cast_time: nil,
        applies_headshot_damage: false,
        burn_damage_per_second: nil,
        is_projectile: false,
        projectile_speed: nil,
        max_damage_per_projectile: nil,
        projectiles_fired_per_second: nil,
        max_range: 10,
        hp: nil,
        is_ultimate: false,
        ultimate_cost: nil,
        name: 'Defense Matrix',
        is_passive: false,
        is_primary_fire: nil,
        is_secondary_fire: false,
        is_beam: false,
        max_beam_damage: nil,
        reload_time: nil,
        fire_rate: nil,
        beam_width: nil
      },
      {
        keybinding: 'LSHIFT',
        cooldown: 4000,
        duration: 2000,
        has_aoe_effect: false,
        aoe_effect_radius: nil,
        base_beam_damage: nil,
        applies_burn: false,
        applies_speed_boost: true,
        applies_stun: false,
        applies_shield: false,
        applies_boop: true,
        boop_distance: 2,
        cast_time: nil,
        applies_headshot_damage: false,
        burn_damage_per_second: nil,
        is_projectile: false,
        projectile_speed: nil,
        max_damage_per_projectile: nil,
        projectiles_fired_per_second: nil,
        max_range: 23.98,
        max_melee_damage: 10,
        hp: nil,
        is_ultimate: false,
        ultimate_cost: nil,
        name: 'Boosters',
        is_passive: false,
        is_primary_fire: nil,
        is_secondary_fire: false,
        is_beam: false,
        max_beam_damage: nil,
        reload_time: nil,
        fire_rate: nil,
        beam_width: nil
      },
      {
        keybinding: 'E',
        cooldown: 8000,
        duration: nil,
        has_aoe_effect: false,
        aoe_effect_radius: nil,
        base_beam_damage: nil,
        applies_burn: false,
        applies_speed_boost: false,
        applies_stun: false,
        applies_shield: false,
        cast_time: 250,
        applies_headshot_damage: false,
        burn_damage_per_second: nil,
        is_projectile: true,
        projectile_speed: 40,
        max_damage_per_projectile: 7,
        projectiles_fired_per_second: nil,
        max_range: nil,
        hp: nil,
        is_ultimate: true,
        ultimate_cost: nil,
        name: nil,
        is_passive: false,
        is_primary_fire: nil,
        is_secondary_fire: false,
        is_beam: false,
        max_beam_damage: nil,
        reload_time: nil,
        fire_rate: nil,
        beam_width: nil
      },
      {
        keybinding: 'E',
        cooldown: 8000,
        duration: nil,
        has_aoe_effect: false,
        aoe_effect_radius: nil,
        base_beam_damage: nil,
        applies_burn: false,
        applies_speed_boost: false,
        applies_stun: false,
        applies_shield: false,
        cast_time: 250,
        applies_headshot_damage: false,
        burn_damage_per_second: nil,
        is_projectile: true,
        projectile_speed: 40,
        max_damage_per_projectile: 7,
        projectiles_fired_per_second: nil,
        max_range: nil,
        hp: nil,
        is_ultimate: true,
        ultimate_cost: nil,
        name: nil,
        is_passive: false,
        is_primary_fire: nil,
        is_secondary_fire: false,
        is_beam: false,
        max_beam_damage: nil,
        reload_time: nil,
        fire_rate: nil,
        beam_width: nil
      },
      {
        keybinding: 'Q',
        cooldown: nil,
        duration: nil,
        has_aoe_effect: true,
        aoe_effect_radius: 20,
        max_aoe_damage: 1000,
        min_aoe_damage: 100,
        base_beam_damage: nil,
        applies_burn: false,
        applies_speed_boost: false,
        applies_stun: false,
        applies_shield: false,
        cast_time: 3000,
        applies_headshot_damage: false,
        burn_damage_per_second: nil,
        is_projectile: false,
        projectile_speed: nil,
        max_damage_per_projectile: nil,
        projectiles_fired_per_second: nil,
        max_range: nil,
        hp: nil,
        is_ultimate: true,
        ultimate_cost: 1540,
        name: 'Self-Destruct',
        is_passive: false,
        is_primary_fire: nil,
        is_secondary_fire: false,
        is_beam: false,
        max_beam_damage: nil,
        reload_time: nil,
        fire_rate: nil,
        beam_width: nil
      },
    ]
  },
  {
    game_id: 1,
    name: "Orisa",
    role_id: 1,
    can_heal_self: false,
    heal_self_strength: nil,
    has_cc: false,
    # cc_strength: ,
    # cc_range: 0,
    hp: 200,
    shield: 0,
    armor: 250,
    has_shield: true,
    shield_hp: 600,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: false,
    # movement_speed: 
    can_fly: false,
    provides_shield: true,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false,
    abilities_attributes: [
      {
        keybinding: 'MOUSE1',
        name: 'Fusion Driver',
        cooldown: nil,
        duration: nil,
        has_aoe_effect: false,
        aoe_effect_radius: nil,
        base_beam_damage: nil,
        applies_burn: false,
        applies_speed_boost: false,
        applies_stun: false,
        applies_shield: false,
        cast_time: nil,
        applies_headshot_damage: true,
        burn_damage_per_second: nil,
        is_projectile: true,
        projectile_speed: 120,
        min_damage_per_projectile: 11,
        max_damage_per_projectile: 11,
        projectiles_fired_per_second: 12,
        max_range: -1,
        hp: nil,
        is_ultimate: false,
        ultimate_cost: nil,
        is_passive: false,
        is_primary_fire: true,
        initial_falloff_distance: -1,
        final_falloff_disance: -1,
        spread_angle: 1.2,
        is_secondary_fire: false,
        is_beam: false,
        max_beam_damage: nil,
        reload_time: 2500,
        fire_rate: 12,
        beam_width: nil,
        applies_self_movement_penalty: true
      },
      {
        keybinding: 'MOUSE2',
        cooldown: 6000,
        duration: 650,
        has_aoe_effect: true,
        aoe_effect_radius: 5,
        base_beam_damage: nil,
        applies_burn: false,
        applies_speed_boost: false,
        applies_stun: false,
        applies_shield: false,
        cast_time: 100,
        applies_headshot_damage: false,
        burn_damage_per_second: nil,
        is_projectile: true,
        projectile_speed: 25,
        max_damage_per_projectile: 0,
        projectiles_fired_per_second: nil,
        max_range: nil,
        hp: nil,
        is_ultimate: false,
        ultimate_cost: nil,
        name: 'Halt!',
        is_passive: false,
        is_primary_fire: nil,
        is_secondary_fire: false,
        is_beam: false,
        max_beam_damage: nil,
        reload_time: nil,
        fire_rate: nil,
        beam_width: nil,
        applies_boop: true,
        boop_distance: nil,
      },
      {
        keybinding: 'LSHIFT',
        cooldown: 10000,
        duration: 4000,
        has_aoe_effect: false,
        aoe_effect_radius: nil,
        base_beam_damage: nil,
        applies_burn: false,
        applies_speed_boost: false,
        applies_stun: false,
        applies_shield: false,
        applies_boop: false,
        boop_distance: nil,
        cast_time: nil,
        applies_headshot_damage: false,
        burn_damage_per_second: nil,
        is_projectile: false,
        projectile_speed: nil,
        max_damage_per_projectile: nil,
        projectiles_fired_per_second: nil,
        max_range: nil,
        max_melee_damage: nil,
        hp: nil,
        is_ultimate: false,
        ultimate_cost: nil,
        name: 'Fortify',
        is_passive: false,
        is_primary_fire: nil,
        is_secondary_fire: false,
        is_beam: false,
        max_beam_damage: nil,
        reload_time: nil,
        fire_rate: nil,
        beam_width: nil,
        applies_self_damage_reduction: true,
      },
      {
        keybinding: 'E',
        cooldown: 10000,
        duration: 20000,
        has_aoe_effect: false,
        aoe_effect_radius: nil,
        base_beam_damage: nil,
        applies_burn: false,
        applies_speed_boost: false,
        applies_stun: false,
        applies_shield: false,
        cast_time: 500,
        applies_headshot_damage: false,
        burn_damage_per_second: nil,
        is_projectile: true,
        projectile_speed: 25,
        max_damage_per_projectile: 7,
        projectiles_fired_per_second: nil,
        max_range: nil,
        hp: 600,
        is_ultimate: false,
        ultimate_cost: nil,
        name: 'Protective Barrier',
        is_passive: false,
        is_primary_fire: nil,
        is_secondary_fire: false,
        is_beam: false,
        max_beam_damage: nil,
        reload_time: nil,
        fire_rate: nil,
        beam_width: nil
      },
      {
        keybinding: 'Q',
        cooldown: nil,
        duration: 15000,
        has_aoe_effect: true,
        aoe_effect_radius: 25,
        base_beam_damage: nil,
        applies_burn: false,
        applies_speed_boost: false,
        applies_stun: false,
        applies_shield: false,
        cast_time: 400,
        applies_headshot_damage: false,
        burn_damage_per_second: nil,
        is_projectile: true,
        projectile_speed: 7,
        max_damage_per_projectile: nil,
        projectiles_fired_per_second: nil,
        max_range: nil,
        hp: 200,
        is_ultimate: true,
        ultimate_cost: 1680,
        name: 'Supercharger',
        is_passive: false,
        is_primary_fire: nil,
        is_secondary_fire: false,
        is_beam: false,
        max_beam_damage: nil,
        reload_time: nil,
        fire_rate: nil,
        beam_width: nil,
        applies_damage_boost: true,
        percent_damage_reduction_self: nil,
        percent_damage_boost_self: nil,
        percent_damage_boost_aoe: 50,
      },
    ]
  },
  {
    game_id: 1,
    name: "Reinhardt",
    role_id: 1,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: ,
    # cc_range: 0,
    hp: 500,
    shield: 0,
    armor: 0,
    has_shield: true,
    shield_hp: 1500,
    melee_primary_fire: true,
    aoe_heal: false,
    aoe_primary: true,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: false,
    provides_shield: true,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false,
    abilities_attributes: [
      {
        name: 'Steadfast',
        is_passive: true,
      },
      {
        keybinding: 'MOUSE1',
        name: 'Rocket Hammer',
        duration: nil,
        has_aoe_effect: false,
        aoe_effect_radius: nil,
        base_beam_damage: nil,
        applies_burn: false,
        applies_speed_boost: false,
        applies_stun: false,
        applies_shield: false,
        cast_time: 432,
        applies_headshot_damage: false,
        burn_damage_per_second: nil,
        is_projectile: false,
        projectile_speed: nil,
        min_damage_per_projectile: nil,
        max_damage_per_projectile: nil,
        projectiles_fired_per_second: nil,
        max_range: 5,
        hp: nil,
        is_ultimate: false,
        ultimate_cost: nil,
        is_passive: false,
        is_primary_fire: true,
        initial_falloff_distance: nil,
        final_falloff_disance: nil,
        spread_angle: nil,
        is_secondary_fire: false,
        is_beam: false,
        max_beam_damage: nil,
        reload_time: nil,
        fire_rate: 1,
        beam_width: nil,
        applies_self_movement_penalty: false
      },
      {
        keybinding: 'MOUSE2',
        cooldown: 5000,
        duration: nil,
        has_aoe_effect: true,
        aoe_effect_radius: 5,
        base_beam_damage: nil,
        applies_burn: false,
        applies_speed_boost: false,
        applies_stun: false,
        applies_shield: false,
        cast_time: nil,
        applies_headshot_damage: false,
        burn_damage_per_second: nil,
        is_projectile: false,
        projectile_speed: nil,
        max_damage_per_projectile: 0,
        projectiles_fired_per_second: nil,
        max_range: nil,
        hp: 1600,
        is_ultimate: false,
        ultimate_cost: nil,
        name: 'Barrier Field',
        is_passive: false,
        is_primary_fire: nil,
        is_secondary_fire: false,
        is_beam: false,
        max_beam_damage: nil,
        reload_time: nil,
        fire_rate: nil,
        beam_width: nil,
        applies_boop: false,
        boop_distance: nil,
      },
      {
        keybinding: 'LSHIFT',
        cooldown: 10000,
        duration: 3000,
        has_aoe_effect: false,
        aoe_effect_radius: nil,
        base_beam_damage: nil,
        applies_burn: false,
        applies_speed_boost: false,
        applies_stun: true,
        applies_shield: false,
        applies_boop: true,
        boop_distance: 2,
        cast_time: 600,
        applies_headshot_damage: false,
        burn_damage_per_second: nil,
        is_projectile: false,
        projectile_speed: nil,
        max_damage_per_projectile: nil,
        projectiles_fired_per_second: nil,
        max_range: 49.5,
        max_melee_damage: 50,
        hp: nil,
        is_ultimate: false,
        ultimate_cost: nil,
        name: 'Charge',
        is_passive: false,
        is_primary_fire: nil,
        is_secondary_fire: false,
        is_beam: false,
        max_beam_damage: nil,
        reload_time: nil,
        fire_rate: nil,
        beam_width: nil,
        applies_self_damage_reduction: true,
      },
      {
        keybinding: 'E',
        cooldown: 6000,
        duration: nil,
        has_aoe_effect: false,
        aoe_effect_radius: nil,
        base_beam_damage: nil,
        applies_burn: false,
        applies_speed_boost: false,
        applies_stun: false,
        applies_shield: false,
        cast_time: 480,
        applies_headshot_damage: false,
        burn_damage_per_second: nil,
        is_projectile: true,
        projectile_speed: 25,
        max_damage_per_projectile: 100,
        projectiles_fired_per_second: nil, 
        max_range: nil,
        hp: nil,
        is_ultimate: false,
        ultimate_cost: nil,
        name: 'Fire Strike',
        is_passive: false,
        is_primary_fire: false,
        is_secondary_fire: false,
        is_beam: false,
        max_beam_damage: nil,
        reload_time: nil,
        fire_rate: nil,
        beam_width: nil
      },
      {
        keybinding: 'Q',
        duration: nil,
        has_aoe_effect: true,
        aoe_effect_radius: 20,
        base_beam_damage: nil,
        applies_burn: false,
        applies_speed_boost: false,
        applies_stun: true,
        stun_duration: 2500,
        applies_shield: false,
        cast_time: 450,
        applies_headshot_damage: false,
        burn_damage_per_second: nil,
        is_projectile: false,
        projectile_speed: nil,
        max_damage_per_projectile: nil,
        projectiles_fired_per_second: nil,
        max_range: 20,
        hp: nil,
        is_ultimate: true,
        ultimate_cost: 1540,
        name: 'Earthshatter',
        is_beam: false,
        max_beam_damage: nil,
        fire_rate: nil,
        beam_width: nil,
        applies_damage_boost: false,
        percent_damage_reduction_self: nil,
        percent_damage_boost_self: nil,
        percent_damage_boost_aoe: nil,
        max_melee_damage: 250,
        min_melee_damage: 50
      },
    ]
  },
  {
    game_id: 1,
    name: "Sigma",
    role_id: 1,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: true,
    cc_strength: 800, # milliseconds duration
    cc_range: 25, # meters
    hp: 300,
    shield: 100,
    armor: 0,
    has_shield: true,
    shield_hp: 700,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: false,
    # movement_speed: 
    can_fly: false,
    provides_shield: true,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false,
    abilities_attributes: [
      {
        keybinding: 'MOUSE1',
        name: 'Hyperspheres',
        duration: nil,
        has_aoe_effect: true,
        aoe_effect_radius: 3,
        base_beam_damage: nil,
        applies_burn: false,
        applies_speed_boost: false,
        applies_stun: false,
        applies_shield: false,
        cast_time: nil,
        applies_headshot_damage: false,
        burn_damage_per_second: nil,
        is_projectile: true,
        projectile_speed: 50,
        min_damage_per_projectile: 55,
        max_damage_per_projectile: 55,
        projectiles_fired_per_second: 1.333,
        max_range: 22,
        hp: nil,
        is_ultimate: false,
        ultimate_cost: nil,
        is_passive: false,
        is_primary_fire: true,
        initial_falloff_distance: nil,
        final_falloff_disance: nil,
        spread_angle: nil,
        is_secondary_fire: false,
        is_beam: false,
        max_beam_damage: nil,
        reload_time: -1,
        fire_rate: 1.5,
        beam_width: nil,
        applies_self_movement_penalty: false,
        min_aoe_damage: 9,
        max_aoe_damage: 30,
        ammo: -1
      },
      {
        keybinding: 'MOUSE2',
        cooldown: 5000,
        duration: -1,
        has_aoe_effect: false,
        aoe_effect_radius: nil,
        base_beam_damage: nil,
        applies_burn: false,
        applies_speed_boost: false,
        applies_stun: false,
        applies_shield: false,
        cast_time: nil,
        applies_headshot_damage: false,
        burn_damage_per_second: nil,
        is_projectile: true,
        projectile_speed: 16.5,
        max_damage_per_projectile: nil,
        projectiles_fired_per_second: nil,
        max_range: -1,
        hp: 700,
        is_ultimate: false,
        ultimate_cost: nil,
        name: 'Experimental Barrier',
        is_passive: false,
        is_primary_fire: nil,
        is_secondary_fire: false,
        is_beam: false,
        max_beam_damage: nil,
        reload_time: nil,
        fire_rate: nil,
        beam_width: nil,
        applies_boop: false,
        boop_distance: nil,
        is_barrier: true,
        # barrier_width:
        # barrier_length:
      },
      {
        keybinding: 'LSHIFT',
        cooldown: 10000,
        duration: 3000,
        has_aoe_effect: false,
        aoe_effect_radius: nil,
        base_beam_damage: nil,
        applies_burn: false,
        applies_speed_boost: false,
        applies_stun: true,
        applies_shield: false,
        applies_boop: true,
        boop_distance: 2,
        cast_time: 600,
        applies_headshot_damage: false,
        burn_damage_per_second: nil,
        is_projectile: false,
        projectile_speed: nil,
        max_damage_per_projectile: nil,
        projectiles_fired_per_second: nil,
        max_range: 49.5,
        max_melee_damage: 50,
        hp: nil,
        is_ultimate: false,
        ultimate_cost: nil,
        name: 'Charge',
        is_passive: false,
        is_primary_fire: nil,
        is_secondary_fire: false,
        is_beam: false,
        max_beam_damage: nil,
        reload_time: nil,
        fire_rate: nil,
        beam_width: nil,
        applies_self_damage_reduction: true,
      },
      {
        keybinding: 'E',
        cooldown: 6000,
        duration: nil,
        has_aoe_effect: false,
        aoe_effect_radius: nil,
        base_beam_damage: nil,
        applies_burn: false,
        applies_speed_boost: false,
        applies_stun: false,
        applies_shield: false,
        cast_time: 480,
        applies_headshot_damage: false,
        burn_damage_per_second: nil,
        is_projectile: true,
        projectile_speed: 25,
        max_damage_per_projectile: 100,
        projectiles_fired_per_second: nil, 
        max_range: nil,
        hp: nil,
        is_ultimate: false,
        ultimate_cost: nil,
        name: 'Fire Strike',
        is_passive: false,
        is_primary_fire: false,
        is_secondary_fire: false,
        is_beam: false,
        max_beam_damage: nil,
        reload_time: nil,
        fire_rate: nil,
        beam_width: nil
      },
      {
        keybinding: 'Q',
        duration: nil,
        has_aoe_effect: true,
        aoe_effect_radius: 20,
        base_beam_damage: nil,
        applies_burn: false,
        applies_speed_boost: false,
        applies_stun: true,
        stun_duration: 2500,
        applies_shield: false,
        cast_time: 450,
        applies_headshot_damage: false,
        burn_damage_per_second: nil,
        is_projectile: false,
        projectile_speed: nil,
        max_damage_per_projectile: nil,
        projectiles_fired_per_second: nil,
        max_range: 20,
        hp: nil,
        is_ultimate: true,
        ultimate_cost: 1540,
        name: 'Earthshatter',
        is_beam: false,
        max_beam_damage: nil,
        fire_rate: nil,
        beam_width: nil,
        applies_damage_boost: false,
        percent_damage_reduction_self: nil,
        percent_damage_boost_self: nil,
        percent_damage_boost_aoe: nil,
        max_melee_damage: 250,
        min_melee_damage: 50
      },
    ]
  },
  {
    game_id: 1,
    name: "Winston",
    role_id: 1,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 350,
    shield: 0,
    armor: 150,
    has_shield: true,
    shield_hp: 700,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: true,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: false,
    provides_shield: true,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false
  },
  {
    game_id: 1,
    name: "Wrecking Ball",
    role_id: 1,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: true,
    cc_strength: 500, # milliseconds duration
    cc_range: 2, # meters
    hp: 500,
    shield: 0,
    armor: 100,
    has_shield: true,
    shield_hp: 100,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: true,
    movement_speed: 10,
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: true
  },
  {
    game_id: 1,
    name: "Zarya",
    role_id: 1,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 200,
    shield: 200,
    armor: 0,
    has_shield: true,
    shield_hp: 200,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: false,
    # movement_speed: 
    can_fly: false,
    provides_shield: true,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: true
  },
  {
    game_id: 1,
    name: "Ashe",
    role_id: 2,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 200,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: false,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: true
  },
  {
    game_id: 1,
    name: "Cassidy",
    role_id: 2,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: true,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 225,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: false,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: true
  },
  {
    game_id: 1,
    name: "Doomfist",
    role_id: 2,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: true,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 250,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false
  },
  {
    game_id: 1,
    name: "Echo",
    role_id: 2,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 200,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: true,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false
  },
  {
    game_id: 1,
    name: "Genji",
    role_id: 2,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 200,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false
  },
  {
    game_id: 1,
    name: "Hanzo",
    role_id: 2,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 200,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: false,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false
  },
  {
    game_id: 1,
    name: "Junkrat",
    role_id: 2,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: true,
    cc_strength: 3000, # milliseconds duration
    cc_range: 0, # meters
    hp: 200,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false
  },
  {
    game_id: 1,
    name: "Pharah",
    role_id: 2,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 200,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: true,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: true,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false
  },
  {
    game_id: 1,
    name: "Sombra",
    role_id: 2,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 200,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: true
  },
  {
    game_id: 1,
    name: "Symmetra",
    role_id: 2,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: true,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 100,
    shield: 125,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: false,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: true,
    has_secondary_fire: true
  },
  {
    game_id: 1,
    name: "Torbjörn",
    role_id: 2,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 200,
    shield: 0,
    armor: 50,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: false,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false
  },
  {
    game_id: 1,
    name: "Tracer",
    role_id: 2,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 150,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: true
  },
  {
    game_id: 1,
    name: "Widowmaker",
    role_id: 2,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 175,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: true
  },
  {
    game_id: 1,
    name: "Zenyatta",
    role_id: 3,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 50,
    shield: 150,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: false,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: true,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false
  },
  {
    game_id: 1,
    name: "Moira",
    role_id: 3,
    can_heal_self: true,
    # heal_self_strength: ,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 200,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: true,
    aoe_primary: false,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: true,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: true
  },
  {
    game_id: 1,
    name: "Mercy",
    role_id: 3,
    can_heal_self: true,
    heal_self_strength: 20, # hp/sec
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 200,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: true,
    provides_shield: false,
    provides_damage_boost: true,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false
  },
  {
    game_id: 1,
    name: "Lúcio",
    role_id: 3,
    can_heal_self: true,
    # heal_self_strength: nil,
    has_cc: true,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 200,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: true,
    aoe_primary: false,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false,
    has_secondary_fire: true
  },
  {
    game_id: 1,
    name: "Brigitte",
    role_id: 3,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: true,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 150,
    shield: 0,
    armor: 50,
    has_shield: true,
    shield_hp: 250,
    melee_primary_fire: true,
    aoe_heal: true,
    aoe_primary: true,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false
  },
  {
    game_id: 1,
    name: "Baptiste",
    role_id: 3,
    can_heal_self: true,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 200,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: true,
    aoe_primary: false,
    has_escape_ability: false,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: true
  },
  {
    game_id: 1,
    name: "Zenyatta",
    role_id: 3,
    can_heal_self: false,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 50,
    shield: 150,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: false,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: true,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false
  },
  {
    game_id: 1,
    name: "Ana",
    role_id: 3,
    can_heal_self: true,
    # heal_self_strength: nil,
    has_cc: true,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 200,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: false,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: true
  },
  {
    game_id: 1,
    name: "Roadhog",
    role_id: 1,
    can_heal_self: true,
    heal_self_strength: 37.5, # amount of healing per second (rename?)
    has_cc: true,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 600,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: false,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false,
    has_secondary_fire: true
  },
  {
    game_id: 1,
    name: "Bastion",
    role_id: 2,
    can_heal_self: true,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 200,
    shield: 0,
    armor: 100,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: false,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: true
  },
  {
    game_id: 1,
    name: "Mei",
    role_id: 2,
    can_heal_self: true,
    # heal_self_strength: nil,
    has_cc: true,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 250,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: false,
    has_secondary_fire: true
  },
  {
    game_id: 1,
    name: "Reaper",
    role_id: 2,
    can_heal_self: true,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 250,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: false,
    aoe_primary: false,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: true,
  },
  {
    game_id: 1,
    name: "Soldier: 76",
    role_id: 2,
    can_heal_self: true,
    # heal_self_strength: nil,
    has_cc: false,
    # cc_strength: 800, # milliseconds duration
    # cc_range: 25, # meters
    hp: 200,
    shield: 0,
    armor: 0,
    has_shield: false,
    shield_hp: 0,
    melee_primary_fire: false,
    aoe_heal: true,
    aoe_primary: false,
    has_escape_ability: true,
    # movement_speed: 
    can_fly: false,
    provides_shield: false,
    provides_damage_boost: false,
    provides_speed_boost: false,
    provides_armor: false,
    is_hitscan: true
  },
]

heroes.each do |hero|
  # for production
  # existing_hero = Hero.find_or_create_by(hero)

  existing_hero = Hero.find_by(name: hero[:name])
  existing_hero.update(hero)
end
